// Generated by CoffeeScript 1.6.1
(function() {
  var chai, expect, fzy;

  fzy = require("../lib/fzy").fzy;

  chai = require("chai");

  chai.Assertion.includeStack = true;

  expect = chai.expect;

  describe("fzy", function() {
    var inputs;
    inputs = [".gitignore", "Gemfile", "LICENSE.txt", "README.md", "Rakefile", "bin/ln2", "lib/ln2.rb", "lib/ln2/Guardfile", "lib/ln2/version.rb", "lib/ln2/watchers.rb", "ln2.gemspec"];
    return it("works on files", function() {
      var f;
      f = function(needle, haystack) {
        return expect(fzy.sort(inputs, needle)[0]).to.eq(haystack);
      };
      f("", ".gitignore");
      f(".g", ".gitignore");
      f("g", "Gemfile");
      f("rf", "Rakefile");
      f("b/l", "bin/ln2");
      f("lb", "lib/ln2.rb");
      f("gsp", "ln2.gemspec");
      f("ln2", "ln2.gemspec");
      return f("m", "README.md");
    });
  });

}).call(this);
